knpu_oauth2_client:
    clients:
        keycloak:
            type: keycloak
            auth_server_url: 'http://localhost:8080'
            realm: 'myapplis'
            client_id: 'Mediateckformation'
            client_secret: 'sYkesnmQSCzf66dqYAFyNePMbEPbKVvz'
            redirect_route: 'oauth_check'
